version: '3'
services:
  eureka-server:
    image: eureka-server:1.0
    container_name: eureka-server
    expose:
    - "8761"
    ports: 
    - 8761:8761 

  user-microservice:
    image: user-microservice:1.0
    #container_name: banking-management-customer-microservice
    ports:
    - "8180"
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://localhost:8761/eureka/ -DDB_USER=root -DDB_PASSWORD=root -DJDBC_URL=jdbc:mariadb://localhost:3306/ticket_booking
      
    links: 
        - eureka-server
  bus-ticket-microservice:
    image: bus-ticket-microservice:1.0
    #container_name: bank-management-employee-microservice
    ports:
    - "8181"
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://localhost:8761/eureka/ -DDB_USER=root -DDB_PASSWORD=root -DJDBC_URL=jdbc:mariadb://localhost:3306/ticket_booking
      
    links: 
        - eureka-server
  ticket-gateway-service:
    image: ticket-booking-gateway:1.0
    #container_name: gateway-microservice
    ports:
    - "8500:8500"
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://localhost:8761/eureka/  #(name of eureka host==eureka container name)
      
    links: 
        - eureka-server
  railway-ticket-microservice:
    image: railway-ticket-microservice:1.0
    #container_name: bank-management-operation-microservice
    ports:
    - "8182"
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://localhost:8761/eureka/ -DDB_USER=root -DDB_PASSWORD=root -DJDBC_URL=jdbc:mariadb://localhost:3306/ticket_booking
      
    links: 
        - eureka-server 

  hotel-booking-microservice:
    image: hotel-booking-microservice:1.0
    #container_name: bank-management-operation-microservice
    ports:
    - "8183"
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://localhost:8761/eureka/ -DDB_USER=root -DDB_PASSWORD=root -DJDBC_URL=jdbc:mariadb://localhost:3306/ticket_booking
      
    links: 
        - eureka-server        
        
  order-microservice:
    image: order-microservice:1.0
    #container_name: bank-management-operation-microservice
    ports:
    - "8184"
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://localhost:8761/eureka/ -DDB_USER=root -DDB_PASSWORD=root -DJDBC_URL=jdbc:mariadb://localhost:3306/ticket_booking
      
    links: 
        - eureka-server      