server:
  port: 8500

spring:
  application:
    name: ticket-gateway-service
  cloud:
    gateway:
      routes:
       - id : user_service
         uri : http://localhost:8180/
         predicates:
           - Path=/user/**
       - id : bus_service
         uri : http://localhost:8181/
         predicates:
           - Path=/bus/**
       - id : railway_service
         uri : http://localhost:8182/
         predicates:
           - Path=/train/**
       - id : hotel_service
         uri : http://localhost:8183/
         predicates:
           - Path=/hotel/**
       - id : order_service
         uri : http://localhost:8184/
         predicates:
           - Path=/order/**
             
eureka:
  client:
    register-with-eureka: true
    service-url: 
         defaultZone :  ${EUREKA_SERVER:http://localhost:8761/eureka/}